name: original_vip
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish 
version: 1.0.6

environment:
  sdk: ^3.6.1


# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.4
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  cloud_firestore: ^5.6.5
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  uuid: ^4.5.1
  go_router: ^14.8.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  intl: ^0.20.2
  liquid_pull_to_refresh: ^3.0.1
  http: ^1.3.0
  firebase_messaging: ^15.2.5
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  flutter_local_notifications: ^19.1.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  upgrader: ^11.3.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path:  "assets/images/app-icon.png"
  min_sdk_android: 21


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ov12.png
    - assets/images/app-icon.png
    - assets/images/o-bgremoved.png
    - assets/images/no-connection.png
    - assets/images/user.png
    - assets/images/empty-cart.png
    - shorebird.yaml
    - assets/credentials/service_account.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
